#!/bin/sh

echo -e "Run E=$1 reconstrcuctions.\n"


echo " ========================================================================="
echo -e " ||\t\t\t\t ebeam: $1 TeV \t\t\t\t||"
echo " ========================================================================="

    
declare -a types=("b")
declare -a bkgtpyes=("2W" "sZ")

for f in "${bkgtpyes[@]}"
do 
    for t in "${types[@]}"
    do 
        FILE="allinone_ISR.C(\"${t}_${f}_${1}\", true, 0)"
        echo -e "\n\n\n\t-------------------------------------------------------------"
        echo -e "\t-----\tRuning $FILE\t-----"
        echo -e "\t-------------------------------------------------------------"
        root -l << EOC 
        .x $FILE 
        .q 
EOC
    done
done 
echo -e "\n\n"

