#!/bin/sh

echo -e "Run E=$1, m=$2 reconstrcuctions.\n"


echo " ========================================================================="
echo -e " ||\t\t\t\t ebeam: $1 TeV \t\t\t\t||"
echo " ========================================================================="
echo -e " ||\t\t\t\t mN: $2 TeV \t\t\t\t||"
echo -e " =========================================================================\n"

    
declare -a types=("s")
declare -a bkgtpyes=("M" "D")

for f in "${bkgtpyes[@]}"
do 
    for t in "${types[@]}"
    do 
        FILE="allinone_ISR.C(\"${t}_${f}_${1}_${2}\", true, 0)"
        echo -e "\n\n\n\t-------------------------------------------------------------"
        echo -e "\t-----\tRuning $FILE\t-----"
        echo -e "\t-------------------------------------------------------------"
        root -l << EOC 
        .x $FILE 
        .q 
EOC
    done
done 
echo -e "\n\n"

