#!/bin/sh

echo -e "Run E=$1, m=$2 reconstrcuctions.\n"





echo " ========================================================================="
echo -e " ||\t\t\t\t ebeam: $1 TeV \t\t\t\t||"
echo " ========================================================================="
echo -e " ||\t\t\t\t mN: $2 TeV \t\t\t\t||"
echo -e " =========================================================================\n"

declare -a types=("i" "s" "t")
for t in "${types[@]}"
do 
    FILE="allinone.C(\"${t}${1}_${2}\", true, 0)"
    echo -e "\n\n\n\t----------------------------------------------"
    echo -e "\t----- Runing $FILE -----"
    echo -e "\t----------------------------------------------"
    root -l << EOC 
    .x $FILE 
    .q 
EOC
done 
    
FILE="allinone.C(\"b${1}\", true, 0)"
echo -e "\t----------------------------------------------"
echo -e "\t----- Runing $FILE -----"
echo -e "\t----------------------------------------------\n\n\n"
root -l << EOC 
.x $FILE 
.q 
EOC
echo -e "\n\n"

